---
- name: Ensure directory for config file exists
  ansible.builtin.file:
    path: /vpn_configs
    state: directory

- name: Copy config file to remote
  ansible.builtin.copy:
    src: "{{ vpn_config_local_path }}"
    # Filename is hash from path to avoid name collision if some of configs have same filename locally.
    # Different configs might have same filename, but path must always be different, therefore different
    # configs will always have different paths.
    dest: "/vpn_configs/{{ vpn_config_local_path | md5 }}.conf"
  register: config
  vars:
    hex: "0123456789abcdef"

- name: Start OpenVPN daemon
  ansible.builtin.command: "openvpn --config {{ config.dest }} --daemon"
