---
- name: Install package
  ansible.builtin.apt:
    pkg: openvpn
    state: present
    update_cache: true

- name: Copy and run each config file
  ansible.builtin.include_tasks: run_config_file.yaml
  loop: "{{ openvpn_configs.files }}"
  loop_control:
    loop_var: vpn_config_local_path
