---
- name: Install package
  ansible.builtin.apt:
    pkg: openvpn
    state: present
    update_cache: true

- name: Ensure directory for config file exists
  ansible.builtin.file:
    path: /vpn_configs
    state: directory

- name: Synchronize openvpn configs
  ansible.posix.synchronize:
    src: "{{ vpn_server_configs_local_path }}"
    dest: "/vpn_configs"
    mode: push
    use_ssh_args: true
    archive: true
    compress: true
    recursive: true

- name: Get paths to configs
  ansible.builtin.find:
    path: /vpn_configs
    file_type: file
    pattern: "*.conf"
    recurse: true
  register: found_openvpn_configs

- name: Start OpenVPN daemon for each config file
  ansible.builtin.command: "openvpn --config {{ item.path }} --daemon"
  loop: "{{ found_openvpn_configs.files }}"
