# More thorough explanation can be found here: https://github.com/LeKSuS-04/ad-infra/wiki/Configuration

yandex_cloud:
  # Folder to create resources in.
  folder_id: your_folder_id_here

  # Zone to create resources in.
  zone: ru-central1-a

  # Can be generated via `yc iam create-token`.
  iam_token: your_iam_token_here

# Directory in `./resources` that contains distributable checkers and services.
src_dirname: ad-training-03-12-2022

# Resources for virtual machines.
virtual_machines: auto

# Credentials from various ForcAD web interfaces.
admin:
  username: admin
  password: password

game:
  # Round duration in seconds.
  round_time: 30

  # Timestamps to start and stop the game. It is recommended to schedule this at least
  # 15 minutes after deploying infrastructure.
  start_time: 2023-12-31 12:00:00
  timezone: Europe/Moscow

  # Default score for tasks.
  default_score: 2500

  # Flag lifetime in rounds.
  flag_lifetime: 5

  # Sets how much points team is earning for an attack (the higher the hardness,
  # the bigger raiting change is). Recommended value range is [5; 20].
  game_hardness: 10.0

  # States if whether a team earns points by attacking zero-rating victium.
  inflation: true

# Description of each task for checksystem.
tasks:
  - name: test_basic_service
    checker: test_service/checker.py
    checker_timeout: 10
    checker_type: hackerdom
    puts: 2
    gets: 2
    places: 5

  - name: test_gevent_service_1
    checker: test_service/gevent_checker.py
    checker_timeout: 10
    checker_type: gevent
    puts: 2
    gets: 2
    places: 5

teams:
  # Whether or not an NPC player is added.
  add_npc: true

  # Amount of players in each team; used to generate correct amount of VPN configs per team.
  players_per_team: 5

  # Password from zip archives with README-s and vpn configs for teams. Can be set to `null` or `~`
  # to create unprotected archives.
  archive_password: null

  # Jinja template for README.md file for each team.
  readme_template: |
    # Welcome to yet another Attack-Defense CTF!

    ### Config for {{ team.name }}
    * Token for jury: `{{ team.token }}`
    * Vulnbox: `ssh {{ team.vulnbox_username }}@{{ team.vulnbox_ip }}`
    * Vulnbox password: `{{ team.vulnbox_password }}`
    * VPN clients for OpenVPN are located inside `vpn/` directory in this archive

    ### VPN network structure
    * Jury system (ForcAD): `10.10.10.10`
    * Vulnboxes: `10.{{ 80 + (config.teams | length) // 256 }}.[1-{{ ((config.teams | length)) % 256 }}].2`
    * Network opens at `{{ config.game.start_time }}` using `{{ config.game.timezone }}` timezone!

    ### Jury config
    * Round time: `{{ forcad.game.round_time }} seconds`
    * Flag lifetime: `{{ forcad.game.flag_lifetime }} rounds`
    * Public scoreboard is available at `http://{{ public_jury_ip }}/`
    * Flag submission protocol is `ructf_http`

    Example of submitting flags via http using curl:
    ```
    curl -X PUT --data '["AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="]' -H "X-Team-Token: deafbeef" http://10.10.10.10/flags
    ```
    Note that each request must not contain more than 100 flags.

    Attack data is available at `/api/client/attack_data/`.

    Example of fetching attack data:
    ```
    curl http://10.10.10.10/api/client/attack_data
    ```


    Good luck, have fun!

    Infrastructure by LeKSuS @ https://github.com/LeKSuS-04.
