---
- name: Get name of ForcAD directory
  ansible.builtin.find:
    path: /
    file_type: directory
    pattern: ForcAD*
  register: found_forcad_dirs

- name: Save ForcAD directory
  ansible.builtin.set_fact:
    forcad_dir: "{{ found_forcad_dirs.files[0].path }}"

- name: Start ForcAD and get team tokens
  become: true
  block:
    - name: Start ForcAD services
      ansible.builtin.command:
        cmd: ./control.py start
        chdir: "{{ forcad_dir }}"

    - name: Retrieve team tokens
      # Services might not be up yet on first couple of runs, so tokens might be anavailable
      retries: 10
      delay: 5
      ansible.builtin.command:
        cmd: ./control.py print_tokens
        chdir: "{{ forcad_dir }}"
      register: team_tokens
      until: team_tokens.rc == 0

    - name: Print team tokens to stdout
      ansible.builtin.debug:
        var: team_tokens.stdout
