from string import ascii_letters, digits

_MAPPING = {
    '$': 'S',
    '-': '_',
    '@': 'a',
    '_': '',
    ' ': '_',
    'a': 'a',
    '6': 'b',
    'в': 'v',
    'r': 'g',
    'д': 'd',
    'e': 'e',
    'ё': 'yo',
    'ж': 'j',
    'з': 'z',
    'и': 'i',
    'й': 'j',
    'к': 'k',
    'л': 'l',
    'м': 'm',
    'н': 'n',
    'o': 'o',
    'п': 'p',
    'p': 'r',
    'c': 's',
    'т': 't',
    'y': 'u',
    'ф': 'f',
    'x': 'h',
    'ц': 'c',
    'ч': 'ch',
    'ш': 'sh',
    'щ': 'shch',
    'ъ': 'y',
    'ы': 'y',
    'ь': 'Y',
    'э': 'e',
    'ю': 'yu',
    'я': 'ya',
    'A': 'A',
    'Б': 'B',
    'B': 'V',
    'Г': 'G',
    'Д': 'D',
    'E': 'E',
    'Ё': 'Yo',
    'Ж': 'J',
    '3': 'Z',
    'И': 'I',
    'Й': 'J',
    'K': 'K',
    'Л': 'L',
    'M': 'M',
    'H': 'N',
    'O': 'O',
    'П': 'P',
    'P': 'R',
    'C': 'S',
    'T': 'T',
    'Y': 'U',
    'Ф': 'F',
    'X': 'H',
    'Ц': 'C',
    'Ч': 'Ch',
    'Ш': 'Sh',
    'Щ': 'Shch',
    'Ъ': 'Y',
    'Ы': 'Y',
    'b': 'Y',
    'Э': 'E',
    'Ю': 'Yu',
    'Я': 'Ya',
}


def normalize_char(char: str) -> str:
    if char in ascii_letters + digits:
        return char
    if char in _MAPPING.keys():
        return _MAPPING[char]
    return '.'
