---
- name: Configure container registry
  hosts: container_registry

  roles:
    # https://www.reddit.com/r/ansible/comments/i5ilw6/comment/g0pj6o5
    - name: Disable unattended-upgrades service
      role: disable_unattended_upgrades

    - name: Install docker engine
      role: install_docker
      vars:
        daemon_config: "{{ docker_daemon_config_file }}"

    - name: Set up container registry
      role: start_container_registry
      vars:
        service_registry_local_path: "{{ hostvars[inventory_hostname].service_registry_local_path }}"
        service_registry_remote_path: /registry
