---
- name: Configure jury host
  hosts: jury
  roles:
    # https://www.reddit.com/r/ansible/comments/i5ilw6/comment/g0pj6o5
    - name: Disable unattended-upgrades service
      role: disable_unattended_upgrades

    - name: Fill hosts entries
      role: fill_hosts_entries

    - name: Install docker engine
      role: install_docker
      vars:
        daemon_config: "{{ docker_daemon_config_file }}"

    - name: Connect to game network
      role: connect_wireguard_client
      vars:
        vpn_client_config_local_path: "{{ vpn_client_file }}"

    - name: Prepare ForcAD
      role: prepare_forcad
      vars:
        forcad_config_local_path: "{{ forcad_config_file }}"
        checkers_local_path: "{{ checkers_path }}"
