---
- name: Configure VPN host
  hosts: vpn

  tasks:
    - name: Run OpenVPN server configs
      ansible.builtin.import_role:
        name: start_openvpn_server

    - name: Schedule network openning
      ansible.builtin.import_role:
        name: schedule_network_openning
