---
- name: Configure VPN host
  hosts: vpn
  strategy: free
  roles:
    # https://www.reddit.com/r/ansible/comments/i5ilw6/comment/g0pj6o5
    - name: Disable unattended-upgrades service
      role: disable_unattended_upgrades

    - name: Run WireGuard server configs
      role: start_wireguard_server

    - name: Schedule network openning
      role: schedule_network_openning
