---
- name: Configure VPN host
  hosts: vpn
  roles:
    - name: Run OpenVPN server configs
      role: start_openvpn_server
      vars:
        vpn_server_config_local_paths: "{{ vpn_server_files }}"

    - name: Schedule network openning
      role: schedule_network_openning
