---
- name: Configure VPN host
  hosts: vpn
  roles:
    # https://www.reddit.com/r/ansible/comments/i5ilw6/comment/g0pj6o5
    - name: Disable unattended-upgrades service
      role: disable_unattended_upgrades

    - name: Run OpenVPN server configs
      role: start_openvpn_server
      vars:
        vpn_server_configs_local_path: "{{ vpn_server_files }}"

    - name: Schedule network openning
      role: schedule_network_openning
