---
- name: Configure vulnbox hosts
  hosts: vulnboxes

  tasks:
    - name: Install docker
      ansible.builtin.import_role:
        name: install_docker
      vars:
        docker_users:
          - "{{ ansible_user }}"
          - "{{ hostvars[inventory_hostname].vars.username }}"

    - name: Connect to game network
      ansible.builtin.import_role:
        name: connect_vpn_client
      vars:
        vpn_client_file: "{{ hostvars[inventory_hostname].vars.vpn_client_file }}"
