---
argument_specs:
  main:
    short_description: Main entrypoint for connect_wireguard_client role
    options:
      vpn_client_config_local_path:
        type: path
        required: true
        description: Path to WireGuard client config on local machine
