---
- name: Install development tools
  ansible.builtin.apt:
    pkg:
      # Versions are not pinned since these packages are not used in any scripts,
      # so even breaking changes to them won't change anything in script runtime
      - python3
      - python3-pip
      - gcc
      - g++
      - gdb
      - golang
      - nodejs
      - npm
      - rustc
      - cargo
      - make
      - cmake
      - vim
      - nano
      - jq
      - git
      - zip
      - unzip
      - netcat
      - net-tools
      - traceroute
      - coreutils
    state: present
    update_cache: true

- name: Install iptables
  ansible.builtin.apt:
    pkg: iptables-persistent
    state: present

# Since all vulnboxes are placed in the same cloud network, we need this to ensure
# that players can access each other only over the VPN, over which we have full control.
# Players might remove this, but it will ultimately lead to their vulnbox being exposed to
# other players while game has not started yet, which will only harm themselves.
- name: Configure iptables
  block:
    - name: Disallow input traffic from any hosts in this network except NAT and DNS server
      ansible.builtin.iptables:
        source: "{{ item.ip }}"
        jump: "{{ item.jump }}"
        chain: INPUT
        action: append
        state: present
      loop:
        # Gateway x.x.x.1
        - ip: "{{ ansible_default_ipv4.gateway }}"
          jump: ACCEPT

        # DNS server x.x.x.2
        - ip: "{{ ansible_default_ipv4.gateway | ansible.utils.ipmath(1) }}"
          jump: ACCEPT

        # All other sources
        - ip: "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ansible.utils.ipaddr('network/prefix') }}"
          jump: DROP

- name: Create user for team
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    append: true
    groups:
      - sudo
    shell: /bin/bash
    create_home: true
    state: present
  register: user

- name: Edit sshd config to allow ssh authentication with password
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication no$"
    line: "PasswordAuthentication yes"
    backrefs: yes
  register: sshd_config

- name: Reload sshd service
  ansible.builtin.systemd:
    name: ssh.service
    state: restarted
  when: sshd_config.changed
