---
- name: Ensure directory for services exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ services_remote_path }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ owner_group }}"

- name: Run services as specified user
  become: true
  become_user: "{{ owner }}"
  block:
    - name: Copy services to vulnbox
      ansible.posix.synchronize:
        # '/' is appended to the path to ensure that only items inside services directories
        # (directories with services themselves) will be copied
        src: "{{ services_local_path + '/' }}"
        dest: "{{ services_remote_path }}"
        mode: push
        use_ssh_args: true
        archive: true
        compress: true
        recursive: true
        perms: true

    - name: Get names of service directories
      ansible.builtin.find:
        path: "{{ services_remote_path }}"
        file_type: directory
      register: services

    - name: Add docker images to registry cache
      ansible.builtin.shell:
        chdir: "{{ item.path }}"
        cmd: docker compose up --build -d
      environment:
        DOCKER_BUILDKIT: "1"
      loop: "{{ services.files }}"
      run_once: true  # Run only once to avoid same image appearing in cache multiple times
      when: ansible_limit is not defined  # Run only if this is the first run

    - name: Run services with docker compose
      ansible.builtin.shell:
        chdir: "{{ item.path }}"
        cmd: docker compose up --build -d
      environment:
        DOCKER_BUILDKIT: "1"
      loop: "{{ services.files }}"
