---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip
      - iptables-persistent
      - ipset
      - at
    state: present
    update_cache: true

- name: Copy ad_net_control script to remote
  ansible.builtin.copy:
    src: ad_net_control
    dest: /
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Make script file executable
  ansible.builtin.file:
    path: /ad_net_control/net_control.py
    mode: 0755

- name: Initialize network
  ansible.builtin.command: "/ad_net_control/net_control.py init --teams {{ team_count }}"

- name: Schedule network openning using `at`
  custom.at:
    command: "/ad_net_control/net_control.py open"
    exact_time: "{{ network_open_time }}"
    unique: true
  environment:
    TZ: "{{ timezone }}"
